# Generated by Django 5.2.6 on 2025-10-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_is_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
